train: True
test: True
module: baseline_adamw
definition: Baseline
monitor: 'val_acc'
monitor_mode: 'max'
lr: 1e-4  # changed here.
max_epochs: 3
mbatch_size: 64  # changed here.
num_workers: 5
exp_dir: /datasets/work/hb-imageclef/work/experiments
dataset_dir: /datasets/work/hb-mlaifsp-mm/source/Datasets
venv_path: /scratch2/nic261/environments/simplified_12_08_22/bin/activate
